import SwiftUI
import StoreKit

struct SettingsView: View {
    @Environment(ZenViewModel.self) private var viewModel
    @Environment(\.dismiss) private var dismiss
    @State private var localShowPaywall = false

    private var cn: Bool { viewModel.L.isChinese }

    var body: some View {
        @Bindable var vm = viewModel

        NavigationStack {
            Form {
                Section(cn ? "语言" : "Language") {
                    Picker(cn ? "显示语言" : "Display Language", selection: $vm.appLanguage) {
                        ForEach(AppLanguage.allCases, id: \.self) { lang in
                            Text(lang.displayName).tag(lang)
                        }
                    }
                }

                Section(cn ? "订阅" : "Subscription") {
                    HStack {
                        Label(cn ? "订阅状态" : "Status", systemImage: "sparkle")
                        Spacer()
                        Text(subscriptionLabel)
                            .foregroundStyle(viewModel.isSubscribed ? .green : .secondary)
                    }

                    if !viewModel.isSubscribed {
                        Button(cn ? "升级订阅" : "Upgrade") {
                            localShowPaywall = true
                        }
                    }

                    // Monthly subscriber → upgrade to yearly
                    if viewModel.subscriptionStatus == .monthly {
                        Button {
                            localShowPaywall = true
                        } label: {
                            HStack {
                                Label(cn ? "升级到年度订阅" : "Upgrade to Yearly", systemImage: "arrow.up.circle")
                                Spacer()
                                if let yearly = viewModel.subscriptionManager.yearlyProduct {
                                    Text("\(yearly.displayPrice)" + (cn ? "/年" : "/yr"))
                                        .font(ZenTheme.caption(13))
                                        .foregroundStyle(ZenTheme.gooseYellow)
                                }
                            }
                        }
                    }

                    // Expiration date
                    if viewModel.isSubscribed, let exp = viewModel.subscriptionManager.expirationDate {
                        HStack {
                            Text(cn ? "到期时间" : "Expires")
                                .foregroundStyle(.secondary)
                            Spacer()
                            Text(exp, style: .date)
                                .font(ZenTheme.caption(13))
                                .foregroundStyle(.secondary)
                        }
                        .font(ZenTheme.caption(13))
                    }
                }

                if viewModel.isSubscribed {
                    Section(header: Text(cn ? "我的专属视角（最多3个）" : "My Custom Perspectives (up to 3)"),
                            footer: Text(cn ? "填写名称即可启用，描述和语气可选。AI视角 + 随机模版视角，共显示6个" : "Fill in a name to enable. Description and tone are optional. AI + random template perspectives, 6 total")) {
                        ForEach(0..<3, id: \.self) { index in
                            perspectiveRow(index: index)
                        }
                    }
                }

                Section(cn ? "免责声明" : "Disclaimer") {
                    VStack(alignment: .leading, spacing: 8) {
                        Label(cn ? "娱乐性质说明" : "Entertainment Disclaimer", systemImage: "info.circle")
                            .font(.headline)

                        Text(cn ? """
                        「禅择 ZenChoice」是一款以娱乐为目的的趣味鼓励应用。\
                        本 App 所提供的所有鼓励内容为算法或AI生成，\
                        仅供娱乐参考，不构成任何专业建议。

                        请勿将本 App 的结果作为实际决策的唯一依据。\
                        对于因使用本 App 产生的任何后果，开发者不承担任何责任。

                        如有心理健康方面的困扰，请寻求专业人士帮助。
                        """ : """
                        ZenChoice is an entertainment app designed to provide fun encouragement. \
                        All encouragement content is generated by algorithms or AI \
                        and is for entertainment purposes only — not professional advice.

                        Do not use this app's output as the sole basis for real decisions. \
                        The developer assumes no liability for any consequences of using this app.

                        If you are experiencing mental health difficulties, please seek professional help.
                        """)
                        .font(ZenTheme.caption(12))
                        .foregroundStyle(.secondary)
                        .lineSpacing(3)
                    }
                    .padding(.vertical, 4)
                }

                Section(cn ? "关于" : "About") {
                    LabeledContent(cn ? "版本" : "Version", value: "2.0.0")
                }
            }
            .navigationTitle(cn ? "设置" : "Settings")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button(cn ? "完成" : "Done") { dismiss() }
                }
            }
            .sheet(isPresented: $localShowPaywall, onDismiss: {
                viewModel.syncSubscriptionStatus()
            }) {
                PaywallView().environment(viewModel)
            }
        }
    }

    private let emojiOptions = ["✨", "🔥", "💎", "🌈", "⚡", "🎭", "👑", "🦄", "🌸", "🎯"]

    @ViewBuilder
    private func perspectiveRow(index: Int) -> some View {
        @Bindable var vm = viewModel
        let label = cn ? "视角 \(index + 1)" : "Perspective \(index + 1)"

        VStack(alignment: .leading, spacing: 8) {
            Text(label)
                .font(ZenTheme.caption(12))
                .foregroundStyle(.secondary)

            HStack(spacing: 8) {
                // Emoji picker
                Menu {
                    ForEach(emojiOptions, id: \.self) { e in
                        Button(e) { vm.customPerspectives[index].emoji = e }
                    }
                } label: {
                    Text(vm.customPerspectives[index].emoji)
                        .font(.title2)
                        .frame(width: 36, height: 36)
                        .background(Color(.systemGray6))
                        .clipShape(RoundedRectangle(cornerRadius: 8))
                }

                VStack(spacing: 6) {
                    TextField(
                        cn ? "名称（如：我奶奶）" : "Name (e.g. My Grandma)",
                        text: $vm.customPerspectives[index].name
                    )
                    .font(ZenTheme.bodyFont(15))

                    TextField(
                        cn ? "描述 - 选填（如：八十岁的慈祥奶奶）" : "Description - optional (e.g. a loving 80-year-old grandma)",
                        text: $vm.customPerspectives[index].description
                    )
                    .font(ZenTheme.bodyFont(13))
                    .foregroundStyle(.secondary)

                    TextField(
                        cn ? "语气 - 选填（如：毒舌、温柔、东北话…）" : "Tone - optional (e.g. sarcastic, gentle…)",
                        text: $vm.customPerspectives[index].tone
                    )
                    .font(ZenTheme.bodyFont(13))
                    .foregroundStyle(.secondary)
                }
            }
        }
        .padding(.vertical, 4)
    }

    private var subscriptionLabel: String {
        switch viewModel.subscriptionStatus {
        case .free: return cn ? "免费版" : "Free"
        case .monthly: return cn ? "月度订阅" : "Monthly"
        case .yearly: return cn ? "年度订阅" : "Yearly"
        }
    }
}

#Preview {
    SettingsView()
        .environment(ZenViewModel())
}
