import SwiftUI
import StoreKit

struct SettingsView: View {
    @Environment(ZenViewModel.self) private var viewModel
    @Environment(\.dismiss) private var dismiss
    @Environment(\.openURL) private var openURL
    @State private var localShowPaywall = false
    @State private var showManageSubscriptions = false

    private var cn: Bool { viewModel.L.isChinese }

    var body: some View {
        @Bindable var vm = viewModel

        NavigationStack {
            Form {
                Section(cn ? "语言" : "Language") {
                    Picker(cn ? "显示语言" : "Display Language", selection: $vm.appLanguage) {
                        ForEach(AppLanguage.allCases, id: \.self) { lang in
                            Text(lang.displayName).tag(lang)
                        }
                    }
                }

                Section(cn ? "订阅" : "Subscription") {
                    HStack {
                        Label(cn ? "订阅状态" : "Status", systemImage: "sparkle")
                        Spacer()
                        Text(subscriptionLabel)
                            .foregroundStyle(viewModel.isSubscribed ? .green : .secondary)
                    }

                    HStack {
                        Label(cn ? "每日次数" : "Daily Limit", systemImage: "flame")
                        Spacer()
                        Text(cn
                             ? "\(viewModel.remainingUsage)/\(viewModel.dailyLimit) 次剩余"
                             : "\(viewModel.remainingUsage)/\(viewModel.dailyLimit) remaining")
                            .font(ZenTheme.caption(13))
                            .foregroundStyle(.secondary)
                    }

                    if !viewModel.isSubscribed || viewModel.subscriptionStatus == .monthly {
                        Button {
                            localShowPaywall = true
                        } label: {
                            HStack {
                                Label(subscribeActionLabel, systemImage: viewModel.isSubscribed ? "arrow.up.circle" : "sparkles")
                                Spacer()
                                Image(systemName: "chevron.right")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }

                    // Expiration date
                    if viewModel.isSubscribed, let exp = viewModel.subscriptionManager.expirationDate {
                        HStack {
                            Text(cn ? "到期时间" : "Expires")
                                .foregroundStyle(.secondary)
                            Spacer()
                            Text(exp, style: .date)
                                .font(ZenTheme.caption(13))
                                .foregroundStyle(.secondary)
                        }
                        .font(ZenTheme.caption(13))

                        Text(cn ? "订阅将在到期前24小时自动续费" : "Subscription auto-renews 24 hours before expiry")
                            .font(ZenTheme.caption(12))
                            .foregroundStyle(.secondary)

                        Button(role: .destructive) {
                            showManageSubscriptions = true
                        } label: {
                            Label(cn ? "取消订阅" : "Cancel Subscription", systemImage: "xmark.circle")
                        }
                    }
                }

                if viewModel.isSubscribed {
                    Section(header: Text(cn ? "我的专属视角（最多3个）" : "My Custom Perspectives (up to 3)"),
                            footer: Text(cn ? "填写名称即可启用，描述和语气可选。AI视角 + 随机模版视角，共显示6个" : "Fill in a name to enable. Description and tone are optional. AI + random template perspectives, 6 total")) {
                        ForEach(0..<3, id: \.self) { index in
                            perspectiveRow(index: index)
                        }
                    }
                }

                Section(cn ? "免责声明" : "Disclaimer") {
                    VStack(alignment: .leading, spacing: 8) {
                        Label(cn ? "娱乐性质说明" : "Entertainment Disclaimer", systemImage: "info.circle")
                            .font(.headline)

                        Text(cn ? """
                        「禅意 ZenChoice」是一款以娱乐为目的的趣味鼓励应用。\
                        本 App 所提供的所有鼓励内容为算法或AI生成，\
                        仅供娱乐参考，不构成任何专业建议。

                        请勿将本 App 的结果作为实际决策的唯一依据。\
                        对于因使用本 App 产生的任何后果，开发者不承担任何责任。

                        如有心理健康方面的困扰，请寻求专业人士帮助。
                        """ : """
                        ZenChoice is an entertainment app designed to provide fun encouragement. \
                        All encouragement content is generated by algorithms or AI \
                        and is for entertainment purposes only — not professional advice.

                        Do not use this app's output as the sole basis for real decisions. \
                        The developer assumes no liability for any consequences of using this app.

                        If you are experiencing mental health difficulties, please seek professional help.
                        """)
                        .font(ZenTheme.caption(12))
                        .foregroundStyle(.secondary)
                        .lineSpacing(3)
                    }
                    .padding(.vertical, 4)
                }

                if viewModel.isSubscribed {
                    Section(cn ? "订阅管理" : "Manage Subscription") {
                        Button(cn ? "管理 Apple 订阅" : "Manage Apple Subscription") {
                            showManageSubscriptions = true
                        }

                        Button(cn ? "恢复购买" : "Restore Purchases") {
                            Task {
                                await viewModel.subscriptionManager.restorePurchases()
                                viewModel.syncSubscriptionStatus()
                            }
                        }
                    }
                }

                Section(cn ? "账号" : "Account") {
                    if let profile = viewModel.authManager.profile {
                        LabeledContent(cn ? "昵称" : "Nickname") {
                            Text(profile.nickname)
                        }
                    }

                    Button(role: .destructive) {
                        viewModel.authManager.signOut()
                        dismiss()
                    } label: {
                        Label(cn ? "退出登录" : "Sign Out", systemImage: "rectangle.portrait.and.arrow.right")
                            .foregroundStyle(.red)
                    }
                }

                Section(cn ? "关于" : "About") {
                    LabeledContent(cn ? "版本" : "Version") {
                        Text(Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0")
                    }
                    Link(cn ? "隐私政策" : "Privacy Policy",
                         destination: URL(string: "https://kyle-zhai.github.io/Zen/privacy.html")!)
                    Link(cn ? "用户协议" : "Terms of Use",
                         destination: URL(string: "https://kyle-zhai.github.io/Zen/terms.html")!)
                }
            }
            .navigationTitle(cn ? "设置" : "Settings")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button(cn ? "完成" : "Done") { dismiss() }
                }
            }
            .sheet(isPresented: $localShowPaywall, onDismiss: {
                viewModel.syncSubscriptionStatus()
            }) {
                PaywallView().environment(viewModel)
            }
            #if os(iOS)
            .manageSubscriptionsSheet(isPresented: $showManageSubscriptions)
            #endif
        }
    }

    private let emojiOptions = ["✨", "🔥", "💎", "🌈", "⚡", "🎭", "👑", "🦄", "🌸", "🎯"]

    @ViewBuilder
    private func perspectiveRow(index: Int) -> some View {
        @Bindable var vm = viewModel
        let label = cn ? "视角 \(index + 1)" : "Perspective \(index + 1)"

        VStack(alignment: .leading, spacing: 8) {
            Text(label)
                .font(ZenTheme.caption(12))
                .foregroundStyle(.secondary)

            HStack(spacing: 8) {
                // Emoji picker
                Menu {
                    ForEach(emojiOptions, id: \.self) { e in
                        Button(e) { vm.customPerspectives[index].emoji = e }
                    }
                } label: {
                    Text(vm.customPerspectives[index].emoji)
                        .font(.title2)
                        .frame(width: 36, height: 36)
                        .background(Color(.systemGray6))
                        .clipShape(RoundedRectangle(cornerRadius: 8))
                }

                VStack(spacing: 6) {
                    TextField(
                        cn ? "名称（如：我奶奶）" : "Name (e.g. My Grandma)",
                        text: $vm.customPerspectives[index].name
                    )
                    .font(ZenTheme.bodyFont(15))

                    TextField(
                        cn ? "描述 - 选填（如：八十岁的慈祥奶奶）" : "Description - optional (e.g. a loving 80-year-old grandma)",
                        text: $vm.customPerspectives[index].description
                    )
                    .font(ZenTheme.bodyFont(13))
                    .foregroundStyle(.secondary)

                    TextField(
                        cn ? "语气 - 选填（如：毒舌、温柔、东北话…）" : "Tone - optional (e.g. sarcastic, gentle…)",
                        text: $vm.customPerspectives[index].tone
                    )
                    .font(ZenTheme.bodyFont(13))
                    .foregroundStyle(.secondary)
                }
            }
        }
        .padding(.vertical, 4)
    }

    private var subscribeActionLabel: String {
        switch viewModel.subscriptionStatus {
        case .free: return cn ? "升级订阅" : "Upgrade"
        case .monthly: return cn ? "升级到年度订阅" : "Upgrade to Yearly"
        case .yearly: return cn ? "管理订阅" : "Manage Subscription"
        }
    }

    private var subscriptionLabel: String {
        switch viewModel.subscriptionStatus {
        case .free: return cn ? "免费版" : "Free"
        case .monthly: return cn ? "月度订阅" : "Monthly"
        case .yearly: return cn ? "年度订阅" : "Yearly"
        }
    }
}

#Preview {
    SettingsView()
        .environment(ZenViewModel())
}
