import SwiftUI

struct SettingsView: View {
    @Environment(ZenViewModel.self) private var viewModel
    @Environment(\.dismiss) private var dismiss
    @State private var localShowPaywall = false

    private var cn: Bool { viewModel.L.isChinese }

    var body: some View {
        @Bindable var vm = viewModel

        NavigationStack {
            Form {
                Section(cn ? "语言" : "Language") {
                    Picker(cn ? "显示语言" : "Display Language", selection: $vm.appLanguage) {
                        ForEach(AppLanguage.allCases, id: \.self) { lang in
                            Text(lang.displayName).tag(lang)
                        }
                    }
                }

                Section(cn ? "个人信息" : "Profile") {
                    TextField(cn ? "你的名字" : "Your name", text: $vm.userName)
                }

                Section {
                    Button {
                        Task {
                            await viewModel.syncProfile()
                            HapticManager.success()
                        }
                    } label: {
                        Label(cn ? "同步资料到云端" : "Sync to cloud", systemImage: "icloud.and.arrow.up")
                    }
                }

                Section(cn ? "订阅" : "Subscription") {
                    HStack {
                        Label(cn ? "订阅状态" : "Status", systemImage: "sparkle")
                        Spacer()
                        Text(subscriptionLabel)
                            .foregroundStyle(viewModel.isSubscribed ? .green : .secondary)
                    }

                    if !viewModel.isSubscribed {
                        Button(cn ? "升级订阅" : "Upgrade") {
                            localShowPaywall = true
                        }
                    }
                }

                Section(cn ? "免责声明" : "Disclaimer") {
                    VStack(alignment: .leading, spacing: 8) {
                        Label(cn ? "娱乐性质说明" : "Entertainment Disclaimer", systemImage: "info.circle")
                            .font(.headline)

                        Text(cn ? """
                        「禅择 ZenChoice」是一款以娱乐为目的的趣味鼓励应用。\
                        本 App 所提供的所有鼓励内容为算法或AI生成，\
                        仅供娱乐参考，不构成任何专业建议。

                        请勿将本 App 的结果作为实际决策的唯一依据。\
                        对于因使用本 App 产生的任何后果，开发者不承担任何责任。

                        如有心理健康方面的困扰，请寻求专业人士帮助。
                        """ : """
                        ZenChoice is an entertainment app designed to provide fun encouragement. \
                        All encouragement content is generated by algorithms or AI \
                        and is for entertainment purposes only — not professional advice.

                        Do not use this app's output as the sole basis for real decisions. \
                        The developer assumes no liability for any consequences of using this app.

                        If you are experiencing mental health difficulties, please seek professional help.
                        """)
                        .font(ZenTheme.caption(12))
                        .foregroundStyle(.secondary)
                        .lineSpacing(3)
                    }
                    .padding(.vertical, 4)
                }

                Section(cn ? "关于" : "About") {
                    LabeledContent(cn ? "版本" : "Version", value: "2.0.0")
                    LabeledContent(cn ? "开发者" : "Developer", value: "Kyle")
                }
            }
            .navigationTitle(cn ? "设置" : "Settings")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button(cn ? "完成" : "Done") { dismiss() }
                }
            }
            .sheet(isPresented: $localShowPaywall) {
                PaywallView().environment(viewModel)
            }
        }
    }

    private var subscriptionLabel: String {
        switch viewModel.subscriptionStatus {
        case .free: return cn ? "免费版" : "Free"
        case .monthly: return cn ? "月度订阅" : "Monthly"
        case .yearly: return cn ? "年度订阅" : "Yearly"
        }
    }
}

#Preview {
    SettingsView()
        .environment(ZenViewModel())
}
